# Generated by Django 6.0.5 on 2026-06-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('observacion', models.CharField(max_length=256)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.materia')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.reservaaula')),
            ],
        ),
    ]
